heat_template_version: 2014-10-16


description: >
  A single Atomic Host with the necessary resources for access and
  configuration.


parameters:

  key_name:
    type: string
    constraints:
    - custom_constraint: nova.keypair

  image:
    type: string
    constraints:
    - custom_constraint: glance.image

  flavor:
    type: string
    constraints:
    - custom_constraint: nova.flavor

  external_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_network:
    type: string
    constraints:
    - custom_constraint: neutron.network

  fixed_subnet:
    type: string
    constraints:
    - custom_constraint: neutron.subnet

  rhn_username:
    type: string

  rhn_password:
    type: string
    hidden: true

resources:

  the_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: the_sg
      description: Ping SSH and HTTP
      rules:
        - protocol: icmp
        - protocol: tcp
          port_range_min: 22
          port_range_max: 22
        - protocol: tcp
          port_range_min: 9090
          port_range_max: 9090

  host:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      key_name: {get_param: key_name}
      networks:
      - port: {get_resource: port}
      admin_user: fedora
      user_data_format: RAW
      user_data: {get_resource: init}

  init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config: {get_resource: RHN_registration}
      - config: {get_resource: cockpit_service}


  cockpit_service:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        password: "atomic"
        chpasswd: { expire: False }
        write_files:
        - encoding: b64
          content: W1VuaXRdCkRlc2NyaXB0aW9uPUNvY2twaXQgV2ViIEludGVyZmFjZQpSZXF1aXJlcz1kb2NrZXIuc2VydmljZQpBZnRlcj1kb2NrZXIuc2VydmljZQoKW1NlcnZpY2VdClJlc3RhcnQ9b24tZmFpbHVyZQpSZXN0YXJ0U2VjPTEwCkV4ZWNTdGFydD0vdXNyL2Jpbi9kb2NrZXIgcnVuIC0tcm0gLS1wcml2aWxlZ2VkIC0tcGlkIGhvc3QgLXYgLzovaG9zdCAtLW5hbWUgJXAgZmVkb3JhL2NvY2twaXR3cyAvY29udGFpbmVyL2F0b21pYy1ydW4gLS1sb2NhbC1zc2gKRXhlY1N0b3A9LS91c3IvYmluL2RvY2tlciBzdG9wIC10IDIgJXAKCltJbnN0YWxsXQpXYW50ZWRCeT1tdWx0aS11c2VyLnRhcmdldAo=
          owner: root:root
          path: /etc/systemd/system/cockpitws.service
          permissions: '0644'
        runcmd:
        - [ systemctl, daemon-reload ]
        - [ systemctl, enable, cockpitws.service ]
        - [ systemctl, start, --no-block, cockpitws.service ]

  RHN_registration:
    type: OS::Heat::SoftwareConfig
    properties:
      config:
        str_replace:
          params:
            $RHN_USERNAME: {get_param: rhn_username}
            $RHN_PASSWORD: {get_param: rhn_password}
          template: {get_file: fragments/rhn-register.sh}

  port:
    type: OS::Neutron::Port
    properties:
      network: {get_param: fixed_network}
      security_groups: [{ get_resource: the_sg }]
      fixed_ips:
      - subnet: {get_param: fixed_subnet}
      replacement_policy: AUTO

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: {get_param: external_network}
      port_id: {get_resource: port}


outputs:
  ip_address:
    description: IP address of the Atomic Host
    value: {get_attr: [floating_ip, floating_ip_address]}
